export const employeeImportHeaders = [
  { label: '*Employee ID', key: 'employeeCode', required: true },
  { label: '*Role', key: 'roleId', required: true },
  { label: '*Last Name', key: 'lastName', required: true },
  { label: '*First Name', key: 'firstName', required: true },
  { label: 'Middle Name', key: 'middleName', required: false },
  { label: 'Suffix', key: 'suffix', required: false },
  { label: '*Date Hired', key: 'hiringDate', required: true },
  { label: '*Date Started', key: 'startDate', required: true },
  {
    label: '*MCash Mobile Number (09xx)',
    key: 'contactNumber',
    required: true,
  },
  {
    label: 'Emergency Contact Number #1 (09xx)',
    key: 'emergencyContactNumber1',
    required: false,
  },
  {
    label: 'Emergency Contact Number #2 (09xx)',
    key: 'emergencyContactNumber2',
    required: false,
  },
  { label: '*Email Address', key: 'emailAddress', required: true },
  { label: '*Street Name, Barangay', key: 'streetAddress', required: true },
  { label: '*City', key: 'cityId', required: true },
  { label: '*Province', key: 'provinceId', required: true },
  { label: '*Country', key: 'countryId', required: true },
  { label: 'Zip Code', key: 'zipCode', required: false },
  { label: '*Place of Birth', key: 'placeOfBirth', required: true },
  { label: '*Birthdate', key: 'birthDate', required: true },
  { label: '*Gender', key: 'gender', required: true },
  { label: '*Civil Status', key: 'civilStatus', required: true },
  { label: '*Nationality', key: 'nationality', required: true },
  {
    label: 'Highest Educational Attainment',
    key: 'educationalAttainment',
    required: false,
  },
  { label: 'School Graduated', key: 'schoolGraduated', required: false },
  { label: 'Course/Degree', key: 'degree', required: false },
  { label: '*Position Title', key: 'positionTitle', required: true },
  { label: 'Day Off', key: 'dayOff', required: false },
  { label: '*Employment Status', key: 'employmentStatus', required: true },
  { label: '*Mode of Payroll', key: 'modeOfPayroll', required: true },
  { label: '*Monthly Basic Pay (in PHP)', key: 'basicPay', required: true },
  // { label: 'Daily Rate (in PHP)', key: 'dailyRate', required: false },
  // {
  //   label: 'Regular Days OT Rate (in PHP)',
  //   key: 'overtimeRateRegDays',
  //   required: false,
  // },
  // {
  //   label: 'Holidays OT Rate (in PHP)',
  //   key: 'overtimeRateHolidays',
  //   required: false,
  // },
  // {
  //   label: 'Rest Days OT Rate (in PHP)',
  //   key: 'overtimeRateRestDays',
  //   required: false,
  // },
  { label: 'Tin Number', key: 'tinNumber', required: false },
  { label: 'Daily Allowance (in PHP)', key: 'allowance', required: false },
  {
    label: 'Vacation Leave Credits',
    key: 'vacationLeaveCredits',
    required: false,
  },
  { label: 'Sick Leave Credits', key: 'sickLeaveCredits', required: false },
  {
    label: 'Service Incentive Leave Credits',
    key: 'serviceIncentiveLeaveCredits',
    required: false,
  },
  {
    label: 'Solo Parent Leave Credits',
    key: 'soloParentLeaveCredits',
    required: false,
  },
  {
    label: 'Paternity Leave Credits',
    key: 'paternityLeaveCredits',
    required: false,
  },
  {
    label: 'Maternity Leave Credits',
    key: 'maternityLeaveCredits',
    required: false,
  },
  {
    label: 'Other Leave Credits',
    key: 'otherLeaveCredits',
    required: false,
  },
  {
    label: 'Emergency Leave Credits',
    key: 'emergencyLeaveCredits',
    required: false,
  },
  {
    label: 'Birthday Leave Credits',
    key: 'birthdayLeaveCredits',
    required: false,
  },
  { label: 'SSS ID', key: 'sssId', required: false },
  {
    label: 'SSS EE Contribution Rate (in PHP)',
    key: 'sssContributionRate',
    required: false,
  },
  {
    label: 'SSS ER Share Rate (in PHP)',
    key: 'sssERShareRate',
    required: false,
  },
  {
    label: 'SSS EC Share Rate (in PHP)',
    key: 'sssECShareRate',
    required: false,
  },
  { label: 'Phil-health ID', key: 'philHealthId', required: false },
  {
    label: 'Phil-health EE Contribution Rate (in PHP)',
    key: 'philHealthContributionRate',
    required: false,
  },
  {
    label: 'Phil-health ER Share Rate (in PHP)',
    key: 'philHealthERShareRate',
    required: false,
  },
  { label: 'Pag-ibig ID', key: 'pagIbigId', required: false },
  {
    label: 'Pag-ibig EE Contribution Rate (in PHP)',
    key: 'pagIbigContributionRate',
    required: false,
  },
  {
    label: 'Pag-ibig ER Share Rate (in PHP)',
    key: 'pagIbigERShareRate',
    required: false,
  },
];

export const attendanceImportHeaders = [
  { label: 'DATE', key: 'date', required: true },
  { label: 'TIME-IN', key: 'timeIn', required: true },
  { label: 'LUNCH-OUT', key: 'lunchTimeOut', required: true },
  { label: 'LUNCH-IN', key: 'lunchTimeIn', required: true },
  { label: 'TIME-OUT', key: 'timeOut', required: true },
  {
    label: 'STATUS (PRESENT/ABSENT/DAY-OFF)',
    key: 'status',
    required: true,
  },
];

export const directPayrollImportHeaders = [
  { label: '*ID', key: 'employeeCode', required: true },
  { label: '*NAME', key: 'employeeFullName', required: true },
  { label: '*MONTH', key: 'businessMonth', required: true },
  { label: '*YEAR', key: 'businessYear', required: true },
  { label: '*CYCLE', key: 'cycle', required: true },
  { label: '*DAYS WORKED', key: 'daysWorked', required: true },
  { label: '*TOTAL WORKING DAYS', key: 'workingDays', required: true },
  { label: '*NET PAY', key: 'netPay', required: true },
];
